import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, currentUser, redirectToSignIn } from "@clerk/nextjs";
import { Nunito } from "next/font/google";
import { ModalProvider } from "@/components/providers/modal-provider";
import { Toaster } from "@/components/ui/toaster";

const font = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dogstagram",
  description: "Generated by create next app",
  icons: [
    {
      url: "/main-logo.png",
      href: "/main-logo.png"
    }
  ]
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ModalProvider />
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
