import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, currentUser, redirectToSignIn } from "@clerk/nextjs";
import { Nunito } from "next/font/google";
import { ModalProvider } from "@/components/providers/modal-provider";

const font = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dogstagram",
  description: "Generated by create next app",
  icons: [
    {
      url: "/main-logo.png",
      href: "/main-logo.png"
    }
  ]
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();

  if (!user || !user.id) {
    redirectToSignIn({ returnBackUrl: `${process.env.NEXT_APPLICATION_URL}/sign-in` })
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ModalProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
